version: '3.8'

services:
  web:
    build: .
    image: hoangphu20/web-web:latest
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team_intro
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./team_project.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: